// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dosrzukjinwpcsetgdmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvc3J6dWtqaW53cGNzZXRnZG1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNDE5NDUsImV4cCI6MjA3MzkxNzk0NX0.8MLXS9E_LmA-Be6M1QeUUa7QWXA3xdxNpYfkZvA1YLw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});